tasks:
  - command: sudo apt-get update && sudo apt-get -y install libvips && npm install && bundle install && npx gulp css && bundle exec jekyll serve

ports:
  - port: 4000
    onOpen: open-preview
    name: Website
    description: Website Preview
    visibility: public
